from django.urls import path
from . import views

urlpatterns = [
    path("vet_profile/", views.vet_profile, name="vet_profile"),
    path("update_vet_profile/", views.update_vet_profile, name="update_vet_profile"),
    path('update_profile_photo/', views.update_profile_photo, name='update_profile_photo'),
    path('delete_profile_photo/', views.delete_profile_photo, name='delete_profile_photo'),
    path("get_all_appointments/", views.get_all_appointments, name="get_all_appointments"),
    path("get_approved_appointments/", views.get_approved_appointments, name="get_approved_appointments"),
    path('approve_appointment/<uuid:app_id>/', views.approve_appointment, name='approve-appointment'),
    path('decline_appointment/<uuid:app_id>/', views.decline_appointment, name='decline-appointment'),
    path('get_horse_details/<uuid:horse_id>/', views.get_horse_details, name='get_horse_details'),
    path('get_horse_medical_records/<uuid:horse_id>/', views.get_horse_medical_records, name='get_horse_medical_records'),
    path('get_horse_treatment_records/<uuid:horse_id>/', views.get_horse_treatment_records, name='get_horse_treatment_records'),
    path('add_medical_record/', views.add_medical_record, name='add_medical_record'),
    path('create_followup_record/', views.create_followup_record, name='create_followup_record'),
    path('update_treatment_outcome/<uuid:treatment_id>/', views.update_treatment_outcome, name='update_treatment_outcome'),
    path('update_medical_record/', views.update_medical_record, name='update_medical_record'),
    path('get_appointment_details/<uuid:app_id>/', views.get_appointment_details, name='get_appointment_details'),
    path('check_horse_access/<uuid:horse_id>/', views.check_horse_access, name='check_horse_access'),
    path('request_horse_access/<uuid:horse_id>/', views.request_horse_access, name='request_horse_access'),
    path("get_all_schedules/", views.get_all_schedules, name="get_all_schedules"),
    path("add_schedule/", views.add_schedule, name="add_schedule"),
    path("get_schedules/", views.get_schedules, name="get_schedules"),
    path("update_schedule_availability/", views.update_schedule_availability, name="update_schedule_availability"),
    path("get_medrec_access/", views.get_medrec_access, name="get_medrec_access"),
    path("change_password/", views.change_password, name="change_password"),
    path("get_all_users/", views.get_all_users, name="get_all_users"),
    path("get_conversation/<uuid:conversation_id>/", views.get_conversation, name="get_conversation"),
    path("get_conversations/", views.get_conversations, name="get_conversations"),
    path("send_message/", views.send_message, name="send_message"),
    path('mark_messages_as_read/<uuid:conversation_id>/', views.mark_messages_as_read, name='mark_messages_as_read'),
]
